/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package thechainstores;

/**
 *
 * @author SARA ALINEZHAD
 */

public class seeDetails extends javax.swing.JFrame {

    /**
     * Creates new form seeDetails
     */
    
   //this is constructor
    public seeDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        seeProductClick = new javax.swing.JLabel();
        seeCategoriesClick = new javax.swing.JLabel();
        goToBuyingPage = new javax.swing.JLabel();
        logoutClick = new javax.swing.JLabel();
        exitClick = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SEEING DETAILS:");

        seeProductClick.setText("2. CLICK TO SEE PRODUCTS!");
        seeProductClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeProductClickMouseClicked(evt);
            }
        });

        seeCategoriesClick.setText("1. CLICK TO SEE CATEGORIES!");
        seeCategoriesClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seeCategoriesClickMouseClicked(evt);
            }
        });

        goToBuyingPage.setText("3. CLICK TO GO TO BUYING/SELLING PAGE");
        goToBuyingPage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToBuyingPageMouseClicked(evt);
            }
        });

        logoutClick.setBackground(new java.awt.Color(0, 255, 153));
        logoutClick.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        logoutClick.setText("LOG OUT");
        logoutClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutClickMouseClicked(evt);
            }
        });

        exitClick.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        exitClick.setForeground(new java.awt.Color(255, 255, 255));
        exitClick.setText("X");
        exitClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitClickMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seeCategoriesClick)
                            .addComponent(seeProductClick)
                            .addComponent(goToBuyingPage))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(exitClick)
                        .addGap(24, 24, 24))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutClick)
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(exitClick, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seeCategoriesClick)
                .addGap(18, 18, 18)
                .addComponent(seeProductClick)
                .addGap(18, 18, 18)
                .addComponent(goToBuyingPage)
                .addGap(24, 24, 24)
                .addComponent(logoutClick)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //leads to category
    private void seeCategoriesClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeCategoriesClickMouseClicked
        new category().setVisible(true);
        //the page will be disposed after
        this.dispose();
    }//GEN-LAST:event_seeCategoriesClickMouseClicked

    //leads to product
    private void seeProductClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seeProductClickMouseClicked
        new products().setVisible(true);
        //the page will be disposed after
        this.dispose();
    }//GEN-LAST:event_seeProductClickMouseClicked

    //leads to login
    private void logoutClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutClickMouseClicked
        new loginPage().setVisible(true);
        //the page will be disposed after
        this.dispose();
    }//GEN-LAST:event_logoutClickMouseClicked

    
    //exits
    private void exitClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitClickMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitClickMouseClicked

    //leads to buyingpage
    private void goToBuyingPageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToBuyingPageMouseClicked
        new buyingPage().setVisible(true);
        //the page will be disposed after
        this.dispose();
    }//GEN-LAST:event_goToBuyingPageMouseClicked

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seeDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seeDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exitClick;
    private javax.swing.JLabel goToBuyingPage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logoutClick;
    private javax.swing.JLabel seeCategoriesClick;
    private javax.swing.JLabel seeProductClick;
    // End of variables declaration//GEN-END:variables
}
